name: "Service action backbone"
description: "Installs poetry and dependencies"

inputs:
  service_name:
    description: "API Service name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Load cached venv if exists
      shell: bash
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: ./${{inputs.service_name}}/.venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/${{inputs.service_name}}/poetry.lock') }}

    - name: Install dependencies if there're no cached dependencies
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        cd ./${{inputs.service_name}}
        poetry install
